### ISSUE TITLE
Функциональная спецификация

### ISSUE THREAD

**Issue by boost-brain** [boost-brain/java-incubator#1]
Разработать функциональную спецификацию проекта "Регистр студентов BoostBrain".
Разработать функциональную схему проекта по функциональной спецификации.

**Comment by ggi-dev** [comment]
взял на себя, буду по возможности доводить до актуальности и добавлять новые требования к проекту

**Comment by ggi-dev** [comment]
Таска бесконечная, её закрываю, и создаю небольшие таски по доработки функциональной спецификации
