### ISSUE TITLE
Сделать одинаковые по нумерации первые страницы сервисов

### ISSUE THREAD

**Issue by BJCreslin** [boost-brain/java-incubator#143]
Сделать одинаковые по нумерации первые страницы сервисов.
А то в Userservice -1.
В проджект сервисе -0

**Comment by ggi-dev** [comment]
в tasks-service тоже с нумерация с 1 (в users-sevice тоже моя реализация). В projects-service используются уже готовые Pageable и Page<ProjectDto> с использованием projectMapper, поэтому когда доделывал, решил пока не трогать эту особенность, так как там не просто коллекция

**Comment by BJCreslin** [comment]
сделал у себя, через костыль
