### ISSUE TITLE
Защитить доступ к сервисам

### ISSUE THREAD

**Issue by boost-brain** [boost-brain/java-incubator#80]
Защитить доступ ко всем сервисам(кроме tasks-service) путем проверки идентификатора сессии(так же, как это сделано в tasks-service).

**Comment by ggi-dev** [comment]
Немного уточню, что для сервиса регистрации пока нет смысла добавлять защиту, так как обращения к нему не могут содержать sessionId.
Так же в users-service будет игнорироваться sessionId при создании сущности пользователя, но он будет не активным, пока модератор или администратор не назначит ему роль с уровнем доступа

**Comment by ggi-dev** [comment]
Добавил возможность  в CheckHeaderSessionBean передавать List<String> skipUriPatterns, в который можно поместить regex на ссылки, пример:
```
List<String> skipUriPatterns = new ArrayList<String>() {{
            add("^\\/api\\/users\\/create$");
            add("^\\/api\\/users\\/update-statuses-for-emails$");
            add("^\\/api\\/users\\/update-status\\/.*");
}};
```
